spring:
  application:
    name: ShopEasy
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shopeasy
    username: postgres
    password: yH7UFQ47
server:
  error:
    include-stacktrace: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html