spring:
  profiles:
    active: dev
  application:
    name: ShopEasy
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: "endereco do banco"
    username: "usuario do banco"
    password: "senha do banco"
server:
  error:
    include-stacktrace: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html